{% set name = "spacy-transformers" %}
{% set module_name = "spacy_transformers" %}
{% set version = "1.1.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dae53acbfaecbcd48ba5e5cbe8ef48390d1130dd0010c1fefc8287eaeb9fbac5


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - spacy >=3.4.0,<4.0.0
    - transformers >=3.4.0,<4.26.0
    - pytorch >=1.6.0
    - srsly >=2.4.0,<3.0.0
    - spacy-alignments >=0.7.2,<1.0.0

test:
#  requires:
#    - pytest
  imports:
    - {{ module_name }}
#  commands:
#    - python -m pytest --tb=native --pyargs {{ module_name }}

about:
  home: https://spacy.io
  license: MIT
  license_file: LICENSE
  summary: Use pretrained transformers like BERT, XLNet and GPT-2 in spaCy
  description: |
    This package provides spaCy components and architectures to use transformer
    models via Hugging Face's transformers in spaCy. The result is convenient
    access to state-of-the-art transformer architectures, such as BERT, GPT-2,
    XLNet, etc.
  doc_url: https://github.com/explosion/spacy-transformers
  dev_url: https://github.com/explosion/spacy-transformers

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
